# 随意配置的, 仅供参考。
mode: rule
mixed-port: 7890
allow-lan: false
log-level: silent # silent/error/warning/info/debug
ipv6: true

secret: ''
external-controller: 127.0.0.1:9090
external-ui: uis/metacubexd # `git clone https://github.com/metacubex/metacubexd.git -b gh-pages <clash_cfg_dir>/uis/metacubexd`
external-ui-name: metacubexd
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip

#geox-url:
#  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
#  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
#  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
#geo-auto-update: false
#geo-update-interval: 24

profile:
  store-selected: true
unified-delay: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
  fallback: []

tun:
  enable: true
  stack: system
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
